server/config/routes.rb
Server::Application.routes.draw do
  #resources :sources

  root :to      => 'home#index'
  get '/events' => 'events#index'
  post '/events/:id/correct' => 'events#correct', :as => 'correct_event'

  resources :corrections
  resources :trucks

  # See how all your routes lay out with "rake routes"
end

server/app/models/correction.rb
class Correction < ActiveRecord::Base
	belongs_to :event

	validates_associated :event
	validates_presence_of :event
	validates_presence_of :start_time
	validates_presence_of :end_time
	validates_presence_of :location
	validates_presence_of :latitude
	validates_presence_of :longitude
	validates_presence_of :formatted_address

	attr_accessor :time_zone

	def start_time
		super.in_time_zone time_zone
	end

	def end_time
		super.in_time_zone time_zone
	end
end

server/app/controllers/corrections_controller.rb
class CorrectionsController < ApplicationController
  # GET /corrections
  # GET /corrections.json
  def index
    @events = Event.all_with_corrections client_time_zone

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: Correction.all }
    end
  end

  # GET /corrections/1
  # GET /corrections/1.json
  def show
    @correction = Correction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @correction }
    end
  end

  # GET /corrections/new
  # GET /corrections/new.json
  def new
    @correction = Correction.new
    @correction.event = Event.find(params[:event_id])
    @correction.event.time_zone = client_time_zone

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @correction }
    end
  end

  # GET /corrections/1/edit
  def edit
    @correction = Correction.find(params[:id])
  end

  # POST /corrections
  # POST /corrections.json
  def create
    @correction = Correction.new(params[:correction])

    respond_to do |format|
      if @correction.save
        format.html { redirect_to @correction, notice: 'Correction was successfully created.' }
        format.json { render json: @correction, status: :created, location: @correction }
      else
        format.html { render action: "new" }
        format.json { render json: @correction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /corrections/1
  # PUT /corrections/1.json
  def update
    @correction = Correction.find(params[:id])

    respond_to do |format|
      if @correction.update_attributes(params[:correction])
        format.html { redirect_to @correction, notice: 'Correction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @correction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corrections/1
  # DELETE /corrections/1.json
  def destroy
    @correction = Correction.find(params[:id])
    @correction.destroy

    respond_to do |format|
      format.html { redirect_to corrections_url }
      format.json { head :no_content }
    end
  end
end

server/app/helpers/corrections_helper.rb
module CorrectionsHelper
end

server/app/views/corrections/_form.html.erb
<%= form_for(@correction) do |f| %>
  <% if @correction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@correction.errors.count, "error") %> prohibited this correction from being saved:</h2>

      <ul>
      <% @correction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :event_id %>

  <div class="field">
    <%= f.label :start_time %>
    <%= render :partial => "shared/datepicker", :locals => { :f => f, :field => :start_time, :default => @correction.event.start_time } %>
  </div>
  <div class="field">
    <%= f.label :end_time %>
    <%= render :partial => "shared/datepicker", :locals => { :f => f, :field => :end_time, :default => @correction.event.end_time } %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= render :partial => "shared/locationpicker", :locals => { :f => f, :latitude => @correction.event.latitude, :longitude => @correction.event.longitude } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/corrections/index.html.erb
<h1>Review Corrections</h1>

<div class="correction-list container">
    <% @events.each do |event| %>
      <%= render :partial => "shared/event", :locals => { :event => event } %>
      <div class="corrections">
        <%= form_for event, :url => correct_event_path(event), :method => :post do |f| %>
          <% event.corrections.each do |correction| %>
            <input type="radio" name="correction_id" value="<%= correction.id %>">
              <%= correction.formatted_address %> : <%= correction.start_time %>
            </input>
          <% end %>
          <div class="actions">
            <%= f.submit "Submit Correction" %>
          </div>
        <% end %>
      </div>
    <% end %>
</div>

server/app/views/corrections/new.html.erb
<div class="container">
	<h1>Submit a correction:</h1>

	<div class="correction-event">
		<%= render :partial => "shared/event", :locals => { :event => @correction.event } %>
	</div>

	<%= render 'form' %>
</div>

server/app/views/corrections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @correction.event.id %>
</p>

<p>
  <b>Start time:</b>
  <%= @correction.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @correction.end_time %>
</p>

<p>
  <b>Latitude:</b>
  <%= @correction.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @correction.longitude %>
</p>

<p>
  <b>Location:</b>
  <%= @correction.location %>
</p>

<p>
  <b>Formatted address:</b>
  <%= @correction.formatted_address %>
</p>