server/config/routes.rb
Server::Application.routes.draw do
  #resources :sources

  root :to      => 'home#index'
  get '/events' => 'events#index'
  post '/events/:id/correct' => 'events#correct', :as => 'correct_event'

  resources :corrections
  resources :trucks

  # See how all your routes lay out with "rake routes"
end

server/app/models/event.rb
require 'haversine_distance'

class Event < ActiveRecord::Base
	has_many :notifications, :dependent => :destroy
	has_many :corrections, :dependent => :destroy
	has_many :tweets, :through => :notifications
	belongs_to :truck

	validates :location, :latitude, :longitude, :start_time, :end_time, :formatted_address, :presence => true

	attr_accessor :distance, :time_zone

	def self.find_nearby sensor, range, date, time_zone
		clause = range_clause sensor, range
		clause[:start_time] = same_day_clause date
		where(clause).each do |event|
			event.time_zone = time_zone
			event.distance = haversine_distance sensor, event
		end.sort {|a, b| a.distance <=> b.distance}
	end

	def self.all_with_corrections time_zone
		all.select {|e| !e.corrections.empty?}.each do |e|
			e.time_zone = time_zone
		end.sort {|a, b| a.start_time <=> b.start_time}
	end

	def self.merge_all!
		all.each do |e|
			if merge_event! e
				logger.debug "Destroy #{e.inspect}"
				e.destroy
			end
		end
	end

	def self.merge_or_save! event
		if !merge_event! event
			event.save
		end

		event
	end

	def merge! event
		event.tweets.each {|t| add_tweet! t}
	end

	def time_zone
		if @time_zone.nil?
			truck.time_zone
		else
			@time_zone
		end
	end

	def time_zone= tz
		@time_zone = tz
		corrections.each {|c| c.time_zone = tz}
		self
	end
	
	def map_url
		"http://maps.google.com/maps?q=#{CGI::escape formatted_address}"
	end

	def start_time
		super.in_time_zone time_zone
	end

	def end_time
		super.in_time_zone time_zone
	end

	def formatted_start_time
		start_time.strftime "%l:%M %P"
	end

	def formatted_distance
		if distance then "%.1f mi" % distance else "n/a" end
	end

	def avatar_url
		truck.profile_image
	end

	def title
		truck.name
	end

	def add_tweet! tweet
		if !tweets.include? tweet
			tweets.push tweet
		end
	end

	def map_image_url
		params = { 
			:size => "48x48",
			:center => "#{latitude},#{longitude}",
			:zoom => 15,
			#:key => "AIzaSyCoNyyQ_MuIRqQhMoNl_VP2C32P0EQM4NI",
			:sensor => "false"
		}

		"http://maps.googleapis.com/maps/api/staticmap?#{params.to_query}"
	end

	def self.range_clause center, range
		{:latitude => mi_to_coord_range(center[:latitude], range), :longitude => mi_to_coord_range(center[:longitude], range)}
	end

	protected

	def self.dist_clause n
		n-0.001..n+0.001
	end

	def self.merge_event! event
		merged = false

		where(:truck_id => event.truck.id, :latitude => dist_clause(event.latitude), :longitude => dist_clause(event.longitude), :start_time => same_day_clause(event.start_time)).where(event.id.nil? ? "id is not ?" : "id != ?", event.id).limit(1).each do |e|
			merged = true
			e.merge! event
		end

		merged
	end

	def self.same_day_clause date
		if date == "all"
			return {}
		end

		date.beginning_of_day..date.beginning_of_day + 1.day
	end

	def self.mi_to_coord_range center, mi
		center - (mi * 0.02)..center + (mi * 0.02)
	end
end

server/app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    cookies[:id] = SecureRandom.hex(10) unless cookies[:id]
    initialize_sensor

    @events = Event.find_nearby @sensor, @sensor[:range], request_date, client_time_zone
    @current_date = formatted_date
    if request_date != "all"
      @previous_day_path = index_path(request_date - 1.day, @sensor[:range])
      @next_day_path = index_path(request_date + 1.day, @sensor[:range])
    end
    @decrease_range_path = index_path(request_date, @sensor[:range] / 2)
    @increase_range_path = index_path(request_date, @sensor[:range] * 2)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  def index_path date, range
    "/events?latitude=#{@sensor[:latitude]}&longitude=#{@sensor[:longitude]}&range=#{range}&date=#{date}" + (params[:mobile] ? "&mobile=true" : "")
  end

  def formatted_date
    date = request_date
    if date == "all"
      "All Dates"
    elsif date.beginning_of_day == Time.now.in_time_zone(client_time_zone).beginning_of_day
      "Today"
    else
      date.strftime "%a, %b %e"
    end
  end

  def request_date
    if params[:date] == "all"
      "all"
    elsif params[:date]
      Time.parse(params[:date]).in_time_zone client_time_zone
    else
      Time.now.in_time_zone client_time_zone
    end
  end

  def initialize_sensor
    range = params[:range] ? params[:range].to_f : 5.0
    if params[:latitude] && params[:longitude]
      @sensor = { :latitude => params[:latitude].to_f, :longitude => params[:longitude].to_f, :range => range }
      save_request!
    else
      @sensor = { :latitude => 37.79457002, :longitude => -122.41135877, :range => range }
    end
  end

  def save_request!
    @request = Request.new({:latitude => params[:latitude], :longitude => params[:longitude], :client_id => cookies[:id]})
    @request.save or logger.warn "Error saving client request: #{@request.errors}"
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # POST /events/1/correct
  # POST /events/1/correct.json
  def correct
    @event = Event.find(params[:id])
    @correction = Correction.find(params[:correction_id])

    @event.update_attributes(ActiveSupport::JSON.decode @correction.to_json(:except => [:id, :event_id, :updated_at]))
    @event.verified = true

    respond_to do |format|
      if @event.save
        Event.merge_all!
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

server/app/helpers/events_helper.rb
module EventsHelper
end

server/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tweet_id %><br />
    <%= f.number_field :tweet_id %>
  </div>
  <div class="field">
    <%= f.label :creation_time %><br />
    <%= f.datetime_select :creation_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

server/app/views/events/index.html.erb
<div class="events">
  <%= render :partial => "shared/date_control", :locals => { :current_date => @current_date, :previous_day_path => @previous_day_path, :next_day_path => @next_day_path } %>
  <%= render(:partial => "shared/event", :collection => @events) || "No food trucks found." %>
  <%= render :partial => "shared/range_control", :locals => { :range => @sensor[:range], :decrease_range_path => @decrease_range_path, :increase_range_path => @increase_range_path } %>
</div>
<% if !params[:mobile] %>
  <%= render :partial => "shared/eventmap", :locals => { :sensor => @sensor, :center => @sensor, :events => @events } %>
<% end %>

server/app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

server/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <%= render :partial => "shared/event", :locals => { :event => @event } %>
</div>

<%= link_to 'Back', events_path %>